### ISSUE TITLE
Remix v2

### ISSUE THREAD

**Issue by ha404** [michaelhelvey/remix-koa-adapter#5]
Any plans to support Remix v2?

**Comment by michaelhelvey** [comment]
I'd love to support Remix v2, but I'm not sure yet what all would be required to make that happen.  I've unfortunately been somewhat unable to follow updates to Remix much lately as my work situation has placed me somewhat outside of the React world.

Ideally I'd have time to dig into Remix v2 at some point to learn what I'll need to do to support that, but I don't have any guarantees on when that will be.  PR's also welcome, of course.
